### ISSUE TITLE
What is left for a 1.0 Release?

### ISSUE THREAD

**Issue by weskoop** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#13]
Do we need anything else?
Does anything else need to be tested or cleaned up?

For me it's working rock solid, just a bit of clean up to do. See the Milestone for details.

**Comment by weskoop** [comment]
@Fannon @llgcode Would love your input.

**Comment by Fannon** [comment]
For me it's rock solid as well. Haven't found a way to break it, yet ;)

The only issue I noticed -  but I think that one is on Bitwig side - is that the controllers are sometimes not properly reset after Bitwig is shutdown. But this also happens to my other controller and also with DrivenByMoss.

**Comment by weskoop** [comment]
Glad it's working well for you!

> The only issue I noticed -  but I think that one is on Bitwig side - is that the controllers are sometimes not properly reset after Bitwig is shutdown. But this also happens to my other controller and also with DrivenByMoss.

I noticed this too, they mentioned it was fixed in 4.1.3, but i still see it happen once in a while on 4.1.4, .5 came out today, haven't tried it yet.

https://downloads-na.bitwig.com/stable/4.1.3/Release-Notes-4.1.3.html

> The exit function of controllers was not always called when quitting Bitwig Studio

**Comment by llgcode** [comment]
Hi,
thanks to ask our feedbacks.

I think 1.0 release is a good idea, it works really well.

One thing that could be great, even if it is already documented, is to have a small screenshot of the midi port configuration on each OS. The first time we do it, we don't really understand why it is done like this.

It have fun playing with it, I play a lot with the builtin sequencer using different midi channel for each 4 tracks.
I do not yet master the session view, it requires more time for me to be effective with it. The problem I found is to be in time with my clip recording (I play guitar), I may need to configure properly pre-roll and other clip settings. Most of the time I need to take the mouse to clean some parts of the clip, because the start or the end is not right.

The things that I've noticed are :

- Be able to set the record length of a clip through "Fixed Length" button (actually missing)
- Capture Midi. Sometimes it trigger the record of a sample 'in note mode' (may be when there's no other clip) and most of the time it activates the overdubbing.
- Play button in launchpad, "sometimes" trigger both the launchpad sequencer and the bitwig play. Sorry to not be more precise. May be related to my preference below.
- the "." ".." buttons are useless for me as I use dual screens
- tap tempo?
- After a while, the launchpad do not communicate with the DAW anymore. I need to reconnect the device. I've fixed it by synchronizing the clock, but I don't really understand what happen here. See screenshot below.

![image](https://user-images.githubusercontent.com/524083/151529171-325ec263-b2d9-492a-b8ab-87c05fc5b343.png)

By setting this, the cool thing here is that tempo is synchronized between the launchpad sequencer and bitwig.

**Comment by weskoop** [comment]
> Hi, thanks to ask our feedbacks.
> 
> I think 1.0 release is a good idea, it works really well.
> 
> One thing that could be great, even if it is already documented, is to have a small screenshot of the midi port configuration on each OS. The first time we do it, we don't really understand why it is done like this.

👍🏻 

> I have fun playing with it, I play a lot with the builtin sequencer using different midi channel for each 4 tracks. I do not yet master the session view, it requires more time for me to be effective with it. The problem I found is to be in time with my clip recording (I play guitar), I may need to configure properly pre-roll and other clip settings. Most of the time I need to take the mouse to clean some parts of the clip, because the start or the end is not right.
> 
> The things that I've noticed are :
> 
> * Be able to set the record length of a clip through "Fixed Length" button (actually missing)

Yes, I've left that off, since it's such a departure in UI from the rest. I would consider adding it, but maybe in future versions. Since the Bitwig version of "Fixed Length" is more full featured, I just left the config to be done on the the computer, and kept the Toggle on the LaunchPad simple.

> * Capture Midi. Sometimes it trigger the record of a sample 'in note mode' (may be when there's no other clip) and most of the time it activates the overdubbing.

"Capture Midi" does not exist in Bitwig. The rest of the behaviour is documented, are you suggesting a change?

> * Play button in launchpad, "sometimes" trigger both the launchpad sequencer and the bitwig play. Sorry to not be more precise. May be related to my preference below.

The play button always starts and stops the Transport, there is only 1 Transport, this is just how both Ableton and Bitwig work.

> * the "." ".." buttons are useless for me as I use dual screens

Interesting, I will try this, and see if we can detect and disable the LEDs on those buttons where there is no toggle. I will see if there is any updates to behaviour needed here.

> * tap tempo?

Tap tempo works, hold shift and Sends/Tap, it's not documented, because the Novation Documentation covers it. The Tempo button is for the internal LP sequencer only.

> * After a while, the launchpad do not communicate with the DAW anymore. I need to reconnect the device. I've fixed it by synchronizing the clock, but I don't really understand what happen here. See screenshot below.
> 
> ![image](https://user-images.githubusercontent.com/524083/151529171-325ec263-b2d9-492a-b8ab-87c05fc5b343.png)
> 
> By setting this, the cool thing here is that tempo is synchronized between the launchpad sequencer and bitwig.
Ahh yes, that should go into the documentation. It's also required to make the LEDs pulse and Blink.

There is already notes about needing to provide a clock for Pulsing/Blinking LEDs. and the differences with Ableton. see here: https://github.com/weskoop/Launchpad-Pro-Mk3-for-Bitwig#errata

I have not had any disconnects, and have had it running for days at a time on my M1 Mac Mini, going through multiple sleep cycles, but keeping Bitwig open.

**Comment by weskoop** [comment]
Tried some of the other Display Modes, seems to play different with each one, also required a re-connect when switching between some of them to get the Follow Orientation mode to work.

I may put in some code to make this smoother or maybe just some notes in the Preferences/Docs

**Comment by weskoop** [comment]
Going to try to wrap this up this weekend!

**Comment by weskoop** [comment]
Done! ✌️

**Comment by llgcode** [comment]
Sorry, for play, record and tap tempo, I was off the mark. 

> I have not had any disconnects, and have had it running for days at a time on my M1 Mac Mini, going through multiple sleep cycles, but keeping Bitwig open.
So you mean with this new settings (midi clock), it will now run without any trouble ?

thansk for the screenshots and all your answers @weskoop. You rock.

**Comment by weskoop** [comment]
> Sorry, for play, record and tap tempo, I was off the mark. 
> 
> 
> 
> > I have not had any disconnects, and have had it running for days at a time on my M1 Mac Mini, going through multiple sleep cycles, but keeping Bitwig open.
> 
> So you mean with this new settings (midi clock), it will now run without any trouble ?
> 
> 
> 
> thansk for the screenshots and all your answers @weskoop. You rock.

thanks so much for all your help @llgcode and @Fannon. I really appreciated the jumping off point and other contributions to get this to a finished release.
