### ISSUE TITLE
TypeScript Typing Issues

### ISSUE THREAD

**Issue by llgcode** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#3]
Hi,
I just wanted to let you know that I've just bought a Launchpad pro mk3 and search a script controller for bitwig. I've quickly test Jürgen but I was lost because I expect to have same native feature but have custom layouts for each node, chord, sequencer.
I think you've started this controller script with that idea in mind to not change the native feature of the controller to have consistent behaviour with the button and the official documentation that I've started to read yesterday. 

I've not tested yet your script, I think I have time this week-end to test it. I've started to read also your README, great to have such a documentation :-).

I am also a typescript developer, I've look at your code to start understand how it work and may be help you if needed.  I'm not familiar with bitwig programming but I have some experiences with web development (and more) on frontend (javascript/typescript) and backend (java server).

I've started a new branch :
https://github.com/llgcode/Launchpad-Pro-Mk3-for-Bitwig/tree/fix-typing-issue

I could open a pull request on it if you are interested to disccuss on it and may be merge it if it make sense.

Thanks for your work.

**Comment by weskoop** [comment]
Hey, thanks for checking it out!

Please test your branch out in Bitwig before you submit a PR.

I'm not usually a Typescript Developer, I just learned it for this project.

**Comment by Fannon** [comment]
Nice. I could also review / contribute maybe. 
I used to be a more active TypeScript developer, but currently I don't get to it as much as I'd like.

**Comment by weskoop** [comment]
@Fannon yep, would be happy for you to review, thanks much. 

I'm C++ all day long (previously php/js/frontend 1996-2016), I think I would have used vanilla JS if your original script didn't use TypeScript; but if I hadn't found your script, I'm not sure I would have done it at all 😛.

**Comment by Fannon** [comment]
Actually using TypeScript helped me a lot when getting started with Bigwig controller scripts, because it came with type safety and code intelligence around Bitwigs controller API, including inline documentation. I'm not sure you would have that with JavaScript only.

The Bigwig API is also not exactly idiomatic JavaScript / TypeScript :)

I'm impressed how well you executed on this given that TS was new to you. Some would maybe be written differently when you have a TS background, but I find it well understandable and structured.
For example, I'm unsure on the `this.parent` pattern. In JavaScript, you have prototype based inheritance and you could access the prototype chain. Or maybe using the `super` keyword is already what you need?
However, I'm not sure whether this would be much of an improvement. I see no issues with having an explicit .parent reference if this is used frequently.

**Comment by Fannon** [comment]
One quick tip, if you are not aware of this already:

If you add comments with a certain syntax, they will be part of what is called "JSDocs". If you place them at the right places, they will become part of your inline documentation of your code. This is very helpful because VSCode and other tools can then relate the code comment to functions, classes etc.

Example:

```ts
// Use this to toggle the modifier buttons for grid Cells.
  protected setGridModButtons(enabled: boolean) {
    ext.buttons.getButton(Button.Duplicate).setShiftedColour(enabled ? Colours.Shifted : Colours.Off);
    ext.buttons.getButton(Button.Clear).setEnabled(enabled).draw(this.getOrientation());;
    ext.buttons.getButton(Button.Duplicate).setEnabled(enabled).draw(this.getOrientation());;
    ext.buttons.getButton(Button.Quantize).setEnabled(enabled).draw(this.getOrientation());;
  }
```

Could be changed to:

```ts
/** Use this to toggle the modifier buttons for grid Cells. */
  protected setGridModButtons(enabled: boolean) {
    ext.buttons.getButton(Button.Duplicate).setShiftedColour(enabled ? Colours.Shifted : Colours.Off);
    ext.buttons.getButton(Button.Clear).setEnabled(enabled).draw(this.getOrientation());;
    ext.buttons.getButton(Button.Duplicate).setEnabled(enabled).draw(this.getOrientation());;
    ext.buttons.getButton(Button.Quantize).setEnabled(enabled).draw(this.getOrientation());;
  }
```

**Comment by weskoop** [comment]
> I'm impressed how well you executed on this given that TS was new to you. Some would maybe be written differently when you have a TS background, but I find it well understandable and structured.

I just followed your lead, but I'm sure it's broken down in some spots. The code comments are pretty sparse. 

Now that it's all working as I hoped, I have less personal interesting in going back for semantic reasons. I also do not have any plans for more features. But i'm happy to look at bug fixes or PRs that do not change the project feature set.

**Comment by weskoop** [comment]
> For example, I'm unsure on the `this.parent` pattern. In JavaScript, you have prototype based inheritance and you could access the prototype chain. Or maybe using the `super` keyword is already what you need? However, adjusting this would more idiomatic, but would not improve the readability or the conciseness of the code much. I see no issues with having an explicit .parent reference if this is used frequently and you prefer this.

this.parent does not refer the the parent class, but a configured parent UI layer. In this case the UI layers (the ones under our control) are simple, mostly rolling back up to the Session Layer. On a more complex UI structure, this would allow you to layer UI over UI over UI, and then jump back through those layers passing Drawing or control back through the stack of Layers. It's a common structure in my other job, and in macOS GUI programming, usually done with pointers, sometimes referred to as Responders.

**Comment by Fannon** [comment]
> Now that it's all working as I hoped, I have less personal interesting in going back for semantic reasons.

Yes, understandable. I also don't like it when people push personal style / architectural preferences on others. Since you're the owner of this project it's your choice anyway. 

> this.parent does not refer the the inheritance, but a parent UI layer. 

Ok, got it. Yesterday I played around with this a bit and also realized that this is not really easy to replace with typical OOP features of TS out of the box. In general OOP starts breaking down in some situations pretty badly and using different architectural patterns on top / besides of it can become helpful or necessary in my experiences.

The idea / architecture is unfamiliar to me but after looking at it for a bit, I think I understand the rationale behind it a bit better. Thanks for the explanations!
